### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by InvisibleRasta** [dimaryaz/dropbox_ext4#4]
not working on debian stretch

**Comment by Nigel-727** [comment]
not working on linux mint either

**Comment by debMan** [comment]
And not working on ubuntu bionic 18.04.

**Comment by dreamer** [comment]
Official Dropbox client brought back support for various filesystems few months ago, I don't think this wrapper is needed any more.

**Comment by Fuseteam** [comment]
It did?

**Comment by dreamer** [comment]
[Dropbox is Bringing Back Support For ZFS, XFS, Btrfs And eCryptFS On Linux](https://itsfoss.com/dropbox-brings-back-linux-filesystem-support/) (July 2019)

**Comment by dimaryaz** [comment]
Yeah, I'll just archive this repo since it's pretty much obsolete now.
